name: MLflow Training CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r Membangun_model/requirements.txt

      - name: Run MLflow Training
        run: |
          python Membangun_model/modelling.py
